export const STATES = Object.freeze({
  RECEIVED: 'RECEIVED',
  VALIDATING: 'VALIDATING',
  CONDITIONING_IDENTITY: 'CONDITIONING_IDENTITY',
  CONDITIONING_OUTFIT: 'CONDITIONING_OUTFIT',
  CONDITIONING_QA: 'CONDITIONING_QA',
  CONDITIONING_RETRY: 'CONDITIONING_RETRY',
  REFERENCES_READY: 'REFERENCES_READY',
  GENERATING_AVATAR: 'GENERATING_AVATAR',
  AVATAR_QA: 'AVATAR_QA',
  AVATAR_RETRY: 'AVATAR_RETRY',
  AVATAR_READY: 'AVATAR_READY',
  GENERATING_OUTFIT: 'GENERATING_OUTFIT',
  OUTFIT_QA: 'OUTFIT_QA',
  OUTFIT_RETRY: 'OUTFIT_RETRY',
  OUTFIT_READY: 'OUTFIT_READY',
  EXPORTING: 'EXPORTING',
  COMPLETED: 'COMPLETED',
  NEEDS_INPUT: 'NEEDS_INPUT',
  FAILED: 'FAILED',
});

export const TERMINAL_STATES = new Set([
  STATES.COMPLETED,
  STATES.NEEDS_INPUT,
  STATES.FAILED,
]);

const transitions = {
  [STATES.RECEIVED]: [STATES.VALIDATING],
  [STATES.VALIDATING]: [STATES.CONDITIONING_IDENTITY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.CONDITIONING_IDENTITY]: [STATES.CONDITIONING_OUTFIT, STATES.CONDITIONING_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.CONDITIONING_OUTFIT]: [STATES.CONDITIONING_QA, STATES.CONDITIONING_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.CONDITIONING_QA]: [STATES.REFERENCES_READY, STATES.CONDITIONING_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.CONDITIONING_RETRY]: [STATES.CONDITIONING_IDENTITY, STATES.FAILED],
  [STATES.REFERENCES_READY]: [STATES.GENERATING_AVATAR, STATES.AVATAR_READY],
  [STATES.GENERATING_AVATAR]: [STATES.AVATAR_QA, STATES.AVATAR_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.AVATAR_QA]: [STATES.AVATAR_READY, STATES.AVATAR_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.AVATAR_RETRY]: [STATES.GENERATING_AVATAR, STATES.FAILED],
  [STATES.AVATAR_READY]: [STATES.GENERATING_OUTFIT],
  [STATES.GENERATING_OUTFIT]: [STATES.OUTFIT_QA, STATES.OUTFIT_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.OUTFIT_QA]: [STATES.OUTFIT_READY, STATES.OUTFIT_RETRY, STATES.NEEDS_INPUT, STATES.FAILED],
  [STATES.OUTFIT_RETRY]: [STATES.GENERATING_OUTFIT, STATES.FAILED],
  [STATES.OUTFIT_READY]: [STATES.EXPORTING],
  [STATES.EXPORTING]: [STATES.COMPLETED, STATES.FAILED],
};

export function assertTransition(from, to) {
  if (!TERMINAL_STATES.has(from) && (to === STATES.FAILED || to === STATES.NEEDS_INPUT)) return;
  if (!(transitions[from] ?? []).includes(to)) {
    throw new Error(`Invalid pipeline state transition: ${from} -> ${to}`);
  }
}

export function isTerminal(state) {
  return TERMINAL_STATES.has(state);
}
